In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np
import matplotlib as plt
from sklearn.preprocessing import LabelEncoder
import pickle

In [ ]:
df =pd.read_csv("/content/drive/MyDrive/ibm project/drive/autos.csv",header=0,sep=',',encoding='Latin1',)

df =pd.read_csv("autos.csv",header=0,sep=',')


In [ ]:
df.seller.value_counts()

privat        371525
gewerblich         3
Name: seller, dtype: int64

In [ ]:
df[df.seller != 'gewerblich']

dateCrawled                                          name  \
0       2016-03-24 11:52:17                                    Golf_3_1.6   
1       2016-03-24 10:58:45                          A5_Sportback_2.7_Tdi   
2       2016-03-14 12:52:21                Jeep_Grand_Cherokee_"Overland"   
3       2016-03-17 16:54:04                            GOLF_4_1_4__3TÜRER   
4       2016-03-31 17:25:20                Skoda_Fabia_1.4_TDI_PD_Classic   
...                     ...                                           ...   
371523  2016-03-14 17:48:27                    Suche_t4___vito_ab_6_sitze   
371524  2016-03-05 19:56:21         Smart_smart_leistungssteigerung_100ps   
371525  2016-03-19 18:57:12            Volkswagen_Multivan_T4_TDI_7DC_UY2   
371526  2016-03-20 19:41:08                        VW_Golf_Kombi_1_9l_TDI   
371527  2016-03-07 19:39:19  BMW_M135i_vollausgestattet_NP_52.720____Euro   

        seller offerType  price   abtest vehicleType  yearOfRegistration  \
0       privat   Angebot    480     test         NaN                1993   
1       privat   Angebot  18300     test       coupe                2011   
2       privat   Angebot   9800     test         suv                2004   
3       privat   Angebot   1500     test  kleinwagen                2001   
4       privat   Angebot   3600     test  kleinwagen                2008   
...        ...       ...    ...      ...         ...                 ...   
371523  privat   Angebot   2200     test         NaN                2005   
371524  privat   Angebot   1199     test      cabrio                2000   
371525  privat   Angebot   9200     test         bus                1996   
371526  privat   Angebot   3400     test       kombi                2002   
371527  privat   Angebot  28990  control   limousine                2013   

          gearbox  powerPS        model  kilometer  monthOfRegistration  \
0         manuell        0         golf     150000                    0   
1         manuell      190          NaN     125000                    5   
2       automatik      163        grand     125000                    8   
3         manuell       75         golf     150000                    6   
4         manuell       69        fabia      90000                    7   
...           ...      ...          ...        ...                  ...   
371523        NaN        0          NaN      20000                    1   
371524  automatik      101       fortwo     125000                    3   
371525    manuell      102  transporter     150000                    3   
371526    manuell      100         golf     150000                    6   
371527    manuell      320      m_reihe      50000                    8   

       fuelType           brand notRepairedDamage          dateCreated  \
0        benzin      volkswagen               NaN  2016-03-24 00:00:00   
1        diesel            audi                ja  2016-03-24 00:00:00   
2        diesel            jeep               NaN  2016-03-14 00:00:00   
3        benzin      volkswagen              nein  2016-03-17 00:00:00   
4        diesel           skoda              nein  2016-03-31 00:00:00   
...         ...             ...               ...                  ...   
371523      NaN  sonstige_autos               NaN  2016-03-14 00:00:00   
371524   benzin           smart              nein  2016-03-05 00:00:00   
371525   diesel      volkswagen              nein  2016-03-19 00:00:00   
371526   diesel      volkswagen               NaN  2016-03-20 00:00:00   
371527   benzin             bmw              nein  2016-03-07 00:00:00   

        nrOfPictures  postalCode             lastSeen  
0                  0       70435  2016-04-07 03:16:57  
1                  0       66954  2016-04-07 01:46:50  
2                  0       90480  2016-04-05 12:47:46  
3                  0       91074  2016-03-17 17:40:17  
4                  0       60437  2016-04-06 10:17:21  
...              ...         ...                  ..

In [ ]:
df=df.drop('seller',1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.


In [ ]:
df.offerType.value_counts()

Angebot    371516
Gesuch         12
Name: offerType, dtype: int64

In [ ]:
df[df.offerType !='Gesuch']

dateCrawled                                          name  \
0       2016-03-24 11:52:17                                    Golf_3_1.6   
1       2016-03-24 10:58:45                          A5_Sportback_2.7_Tdi   
2       2016-03-14 12:52:21                Jeep_Grand_Cherokee_"Overland"   
3       2016-03-17 16:54:04                            GOLF_4_1_4__3TÜRER   
4       2016-03-31 17:25:20                Skoda_Fabia_1.4_TDI_PD_Classic   
...                     ...                                           ...   
371523  2016-03-14 17:48:27                    Suche_t4___vito_ab_6_sitze   
371524  2016-03-05 19:56:21         Smart_smart_leistungssteigerung_100ps   
371525  2016-03-19 18:57:12            Volkswagen_Multivan_T4_TDI_7DC_UY2   
371526  2016-03-20 19:41:08                        VW_Golf_Kombi_1_9l_TDI   
371527  2016-03-07 19:39:19  BMW_M135i_vollausgestattet_NP_52.720____Euro   

       offerType  price   abtest vehicleType  yearOfRegistration    gearbox  \
0        Angebot    480     test         NaN                1993    manuell   
1        Angebot  18300     test       coupe                2011    manuell   
2        Angebot   9800     test         suv                2004  automatik   
3        Angebot   1500     test  kleinwagen                2001    manuell   
4        Angebot   3600     test  kleinwagen                2008    manuell   
...          ...    ...      ...         ...                 ...        ...   
371523   Angebot   2200     test         NaN                2005        NaN   
371524   Angebot   1199     test      cabrio                2000  automatik   
371525   Angebot   9200     test         bus                1996    manuell   
371526   Angebot   3400     test       kombi                2002    manuell   
371527   Angebot  28990  control   limousine                2013    manuell   

        powerPS        model  kilometer  monthOfRegistration fuelType  \
0             0         golf     150000                    0   benzin   
1           190          NaN     125000                    5   diesel   
2           163        grand     125000                    8   diesel   
3            75         golf     150000                    6   benzin   
4            69        fabia      90000                    7   diesel   
...         ...          ...        ...                  ...      ...   
371523        0          NaN      20000                    1      NaN   
371524      101       fortwo     125000                    3   benzin   
371525      102  transporter     150000                    3   diesel   
371526      100         golf     150000                    6   diesel   
371527      320      m_reihe      50000                    8   benzin   

                 brand notRepairedDamage          dateCreated  nrOfPictures  \
0           volkswagen               NaN  2016-03-24 00:00:00             0   
1                 audi                ja  2016-03-24 00:00:00             0   
2                 jeep               NaN  2016-03-14 00:00:00             0   
3           volkswagen              nein  2016-03-17 00:00:00             0   
4                skoda              nein  2016-03-31 00:00:00             0   
...                ...               ...                  ...           ...   
371523  sonstige_autos               NaN  2016-03-14 00:00:00             0   
371524           smart              nein  2016-03-05 00:00:00             0   
371525      volkswagen              nein  2016-03-19 00:00:00             0   
371526      volkswagen               NaN  2016-03-20 00:00:00             0   
371527             bmw              nein  2016-03-07 00:00:00             0   

        postalCode             lastSeen  
0            70435  2016-04-07 03:16:57  
1            66954  2016-04-07 01:46:50  
2            90480  2016-04-05 12:47:46  
3            91074  2016-03-17 17:40:17  
4            60437  2016-04-06 10:17:21  
...            ...                  ...  
371523       39576  20

In [ ]:
df=df.drop('offerType',1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  """Entry point for launching an IPython kernel.


In [ ]:
df.shape

(371528, 18)

In [ ]:
df=df[(df.powerPS > 50)&(df.powerPS <900)]
df.shape

(319709, 18)

In [ ]:
df=df[(df.yearOfRegistration >=1950)&(df.yearOfRegistration <2017)]
df.shape

(309171, 18)

In [ ]:
df.drop(['name','abtest','dateCrawled','nrOfPictures','lastSeen','postalCode','dateCreated'],axis='columns',inplace=True)

In [ ]:
new_df =df.copy()
new_df =new_df.drop_duplicates(['price','vehicleType','yearOfRegistration','gearbox','powerPS','model','kilometer','monthOfRegistration','fuelType','notRepairedDamage'])

In [ ]:
new_df.gearbox.replace(('manuell','automatik'),('manual','automatic'),inplace=True)
new_df.fuelType.replace(('benzin','andere','elektro'),('petrol','others','electric'),inplace=True)
new_df.vehicleType.replace(('kleinwagen','cabria','kombi','andere'),('small car','convertible','combination','others'),inplace=True)
new_df.notRepairedDamage.replace(('ja','nein'),('Yes','No'),inplace=True)

In [ ]:
new_df =new_df[(new_df.price >=100)&(new_df.price <=150000)]

In [ ]:
new_df['notRepairedDamage'].fillna(value='not-declared',inplace=True)
new_df['fuelType'].fillna(value='not-declared',inplace=True)
new_df['gearbox'].fillna(value='not-declared',inplace=True)
new_df['vehicleType'].fillna(value='not-declared',inplace=True)
new_df['model'].fillna(value='not-declared',inplace=True)


In [ ]:
new_df.to_csv("autos_prep.csv")

In [ ]:
labels =['gearbox','notRepairedDamage','model','brand','fuelType','vehicleType']
mapper={}
for i in labels:
    mapper[i]=LabelEncoder()
    mapper[i].fit(new_df[i])
    tr=mapper[i].transform(new_df[i])
    np.save(str('classes'+i+'.npy'),mapper[i].classes_)
    print(i,":",mapper[i])
    new_df.loc[:,i+'_labels']=pd.Series(tr,index=new_df.index)
labeled=new_df[['price','yearOfRegistration','powerPS','kilometer','monthOfRegistration']+[x+"_labels" for x in labels]]
print(labeled.columns)

gearbox : LabelEncoder()
notRepairedDamage : LabelEncoder()
model : LabelEncoder()
brand : LabelEncoder()
fuelType : LabelEncoder()
vehicleType : LabelEncoder()
Index(['price', 'yearOfRegistration', 'powerPS', 'kilometer',
       'monthOfRegistration', 'gearbox_labels', 'notRepairedDamage_labels',
       'model_labels', 'brand_labels', 'fuelType_labels',
       'vehicleType_labels'],
      dtype='object')


In [ ]:
Y=labeled.iloc[:,0].values
X =labeled.iloc[:,1:].values

Y =Y.reshape(-1,1)

In [ ]:
from sklearn.model_selection import cross_val_score,train_test_split
X_train,X_test,Y_train,Y_test =train_test_split(X,Y,test_size=0.3,random_state=3)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

regressor =RandomForestRegressor(n_estimators=1500,max_depth=14,random_state=34)

regressor.fit(X_train, np.ravel(Y_train,order='C'))

RandomForestRegressor(max_depth=14, n_estimators=1500, random_state=34)

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score

regressor1 =RandomForestRegressor(n_estimators=1000,max_depth=10,random_state=34)

regressor1.fit(X_train, np.ravel(Y_train,order='C'))

RandomForestRegressor(max_depth=10, n_estimators=1000, random_state=34)

In [ ]:
r1_pred =regressor1.predict(X_test)
print(r2_score(Y_test,r1_pred))

0.8358948448938501


In [ ]:
r_pred =regressor.predict(X_test)
print(r2_score(Y_test,r_pred))
#nest ="1500" rstate="34"

0.8590576549469706


In [ ]:
Y_test.ndim

2

In [ ]:
Y_test

array([[10000],
       [ 1500],
       [ 2699],
       ...,
       [ 1300],
       [ 5000],
       [  777]])

In [ ]:
r_pred.ndim

1

In [ ]:
Y_test.resize(83574, refcheck=False)
Y_test.ndim

1

In [ ]:
Y_test.resize(14964,refcheck=False)
len(Y_test)

14964

In [ ]:
len(r1_pred)

83574

In [ ]:
r1_pred.resize(14964,refcheck=False)

In [ ]:
print(len(r_pred),len(Y_test))

83574 14964


In [ ]:
profit=pd.DataFrame({'Actual_y_value':Y_test,'Random_forest':r1_pred})
profit

Actual_y_value  Random_forest
0               10000   10017.428422
1                1500    1166.930360
2                2699    2733.071524
3                3499    2844.872891
4               16490   12447.276237
...               ...            ...
14959            1950    2473.828909
14960            1100     806.824995
14961             550    1166.930360
14962           10400   11853.403457
14963           10700    8917.949454

[14964 rows x 2 columns]

In [ ]:
r_pred.resize(14964,refcheck=False)

In [ ]:
from sklearn import metrics
metrics.accuracy_score(Y_test,r_pred)

ValueError: ignored

In [ ]:
from sklearn import metrics
confusion_matrix =metrics.confusion_matrix(Y_test,r_pred)
cm_display = metrics.ConfusionMatrixDisplay(confusion_matrix= confusion_matrix,display_labels = [False,True])

ValueError: ignored

In [ ]:
r_pred.resize(14964, refcheck=False)

In [ ]:
len(Y_test)

14964

In [ ]:
profit=pd.DataFrame({'Actual_y_value':Y_test,'Random_forest':r_pred})
profit

Actual_y_value  Random_forest
0               10000   10459.526315
1                1500    1097.900782
2                2699    2738.417361
3                3499    2879.348287
4               16490   13095.992143
...               ...            ...
14959            1950    2361.235800
14960            1100     553.253858
14961             550     839.977475
14962           10400   10944.709533
14963           10700       0.000000

[14964 rows x 2 columns]

In [ ]:

from sklearn.metrics import mean_squared_error
print(mean_squared_error(Y_test, r_pred))

8902656.720547473


In [ ]:
from sklearn.metrics import mean_absolute_error
print(mean_absolute_error(Y_test,r_pred))

1377.676754526743


In [ ]:
r_pred.resize(14964,refcheck=False)
print(len(Y_test),len(r_pred))

14964 14964


In [ ]:
r_pred =regressor.predict(X_test)
print(r2_score(Y_test,r_pred))
#nest ="1000" rstate="34"

ValueError: ignored

In [ ]:
r_pred =regressor.predict(X_test)
print(r2_score(Y_test,r_pred))
#nest="15000" rstate="42"

In [ ]:
r_pred =regressor.predict(X_test)
print(r2_score(Y_test,r_pred))

ValueError: ignored

In [ ]:
from sklearn.linear_model import Ridge

In [ ]:
r=Ridge()

In [ ]:
r.fit(X_train,Y_train)

In [ ]:
ridge_pred=r.predict(X_test)
ridge_pred

In [ ]:
ridge_pred_train = r.predict(X_train)
ridge_pred_train

In [ ]:
from sklearn.metrics import r2_score


y_pred =r.predict(X_test)
print(r2_score(Y_test,y_pred))

In [ ]:
from sklearn.linear_model import Lasso

In [ ]:
l=Lasso()

In [ ]:
l.fit(X_train,Y_train)

Lasso()

In [ ]:
lasso_pred=l.predict(X_test)
lasso_pred

array([7188.24580173, -976.8224098 , 1261.14952673, ..., 1374.24349036,
       2635.08402186, -698.27210988])

In [ ]:
lasso_pred_train = l.predict(X_train)
lasso_pred_train

In [ ]:
Y_test

In [ ]:
r_pred

In [ ]:
ridge_pred.ndim

In [ ]:
lasso_pred

array([7188.24580173, -976.8224098 , 1261.14952673, ..., 1374.24349036,
       2635.08402186, -698.27210988])

In [ ]:
Y_test.resize(83574,)
Y_test.ndim

ValueError: ignored

In [ ]:
ridge_pred.resize(83574,refcheck=False)

NameError: ignored

In [ ]:
lasso_pred.resize(83574,)

In [ ]:
profit=pd.DataFrame({'Actual_y_value':Y_test,'Ridge_pred':ridge_pred,'Lasso_pred':lasso_pred,'Random_forest':r_pred})
profit

NameError: ignored

In [ ]:
from sklearn.metrics import r2_score
from sklearn import metrics 

y_pred =l.predict(X_test)
print(r2_score(Y_test,y_pred))

print(metrics.mean_squared_error(Y_test,ridge_pred))
print(metrics.mean_squared_error(Y_test,lasso_pred))
print(metrics.mean_squared_error(Y_test,r1_pred))
# RMSE

print(np.sqrt(metrics.mean_squared_error(Y_test,ridge_pred)))
print(np.sqrt(metrics.mean_squared_error(Y_test,lasso_pred)))
print(np.sqrt(metrics.mean_squared_error(Y_test,r1_pred)))
## R2-score

print(metrics.r2_score(Y_test,ridge_pred))
print(metrics.r2_score(Y_test,lasso_pred))
print(metrics.r2_score(Y_test,r1_pred))
# R2 score on Training data

print(metrics.r2_score(Y_train,ridge_pred_train))
print(metrics.r2_score(Y_train,lasso_pred_train))
print(metrics.r2_score(Y_train,r1_pred_train))


ValueError: ignored

In [ ]:

Y_test

array([[10000],
       [ 1500],
       [ 2699],
       ...,
       [ 1300],
       [ 5000],
       [  777]], dtype=int64)

In [ ]:
ridge_pred

array([[7193.41341814],
       [-975.04139152],
       [1263.15985462],
       ...,
       [1374.45640377],
       [2629.93249276],
       [-697.96598737]])

In [ ]:
lasso_pred

array([7188.24580173, -976.8224098 , 1261.14952673, ..., 1374.24349036,
       2635.08402186, -698.27210988])

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
MLR= LinearRegression()

In [ ]:
MLR.fit(X_train,Y_train)

LinearRegression()

In [ ]:
m_pred=MLR.predict(X_test)
m_pred
m_pred.resize(83574,)
m_pred.ndim
lasso_pred.ndim
r_pred.ndim
ridge_pred.ndim
Y_test.resize(83574,)

NameError: name 'lasso_pred' is not defined

In [ ]:
profit=pd.DataFrame({'Actual_y_value':Y_test,'Ridge_pred':ridge_pred,'Lasso_pred':lasso_pred,'Random_forest':r_pred,'multiple_linear':m_pred})
profit.head(10)

In [ ]:
filename = 'MLR.sav'
pickle.dump(MLR,open(filename,'wb'))


In [ ]:
filename = 'ridge.sav'
pickle.dump(r,open(filename,'wb'))

In [ ]:
filename = 'lasso.sav'
pickle.dump(l,open(filename,'wb'))

In [ ]:
filename = 'resale_model.sav'
pickle.dump(l,open(filename,'wb'))